Repository MicrosoftDocs/azure-docs.es-es, pull requests merged in 2019-10, with the labels that each got.

#684 Fix title
  articles/azure-functions/functions-overview.md
Labels: Accepted, Linguistic Suggestion

#682 Fix titles
  articles/virtual-machines/linux/quick-create-powershell.md
Labels: Accepted, Linguistic Suggestion

#686 Corrección de sintáxis
  articles/dms/dms-overview.md
Labels: Accepted

#687 Fix blanks
  articles/azure-resource-manager/resource-group-overview.md
Labels: In Progress
