Repository MicrosoftDocs/azure-docs.es-es, pull requests merged in 2019-03, with the labels that each got.

#285 Actualización a "App service web tutorial custom domain"
  articles/app-service/app-service-web-tutorial-custom-domain.md
Labels: Linguistic Suggestion, Partially Accepted

#305 Fix typo
  articles/storage/blobs/data-lake-storage-use-databricks-spark.md
Labels: Accepted, Linguistic Suggestion

#304 Fix typo
  articles/storage/blobs/data-lake-storage-quickstart-create-databricks-account.md
Labels: Accepted, Technical Issue

#293 Linea 406 No comprensible
  articles/governance/policy/tutorials/create-and-manage.md
Labels: Linguistic Suggestion, Partially Accepted

#294 Actualización de "App service linux java"
  articles/app-service/containers/app-service-linux-java.md
Labels: Linguistic Suggestion, Partially Accepted

#308 Contexto linea 71
  articles/sql-database/sql-database-paas-vs-sql-server-iaas.md
Labels: Linguistic Suggestion, Partially Accepted

#311 feedback
  articles/virtual-network/virtual-networks-overview.md
Labels: Accepted, Linguistic Suggestion

#312 Feedback
  articles/security/security-virtual-machines-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#313 Feedback
  articles/security/security-network-overview.md
Labels: Accepted, Linguistic Suggestion

#314 Feedback
  articles/security/security-management-and-monitoring-overview.md
Labels: Linguistic Suggestion

#315 Corrección en la redacción
  articles/active-directory/fundamentals/active-directory-whatis.md
Labels: Accepted, Linguistic Suggestion

#316 Corrección en la redacción
  articles/active-directory/fundamentals/active-directory-whatis.md
Labels: Accepted, Linguistic Suggestion

#317 Corrección en la redacción
  articles/active-directory/fundamentals/active-directory-whatis.md
Labels: Linguistic Suggestion

#323 Linea 83 Complemento de párrafo
  articles/sql-database/sql-database-import.md
Labels: Linguistic Suggestion

#326 Corrección en la redacción y traducción
  articles/security/security-identity-management-overview.md
Labels: Linguistic Suggestion, Rejected

#331 Feedback
  articles/storage/blobs/storage-quickstart-blobs-powershell.md
Labels: Accepted, Linguistic Suggestion

#339 Feedback
  includes/azure-storage-limits.md
Labels: In Progress, Linguistic Suggestion
