Repository MicrosoftDocs/azure-docs.es-es, pull requests merged in 2019-02, with the labels that each got.

#271 Error gramatical
  articles/virtual-machines/windows/index.yml
Labels: Accepted, Linguistic Suggestion

#263 Corrección de redaccion
  articles/app-service/app-service-web-tutorial-php-mysql.md
Labels: Linguistic Suggestion, Partially Accepted

#272 Mejor contexto liena 37
  articles/azure-resource-manager/resource-group-overview.md
Labels: Linguistic Suggestion, Partially Accepted

#278 Fix missing
  articles/storage/blobs/data-lake-storage-use-databricks-spark.md
Labels: Accepted, Linguistic Suggestion

#277 Fix missing
  articles/storage/blobs/data-lake-storage-quickstart-create-databricks-account.md
Labels: Accepted, Linguistic Suggestion

#275 Fix missing
  articles/azure-databricks/databricks-stream-from-eventhubs.md
Labels: Accepted, Linguistic Suggestion

#276 Fix missing
  articles/azure-databricks/quickstart-create-databricks-workspace-resource-manager-template.md
Labels: Accepted, Linguistic Suggestion

#286 Error de contexto y traducción linea 12
  articles/cost-management/index.yml
Labels: Accepted, Linguistic Suggestion

#289 Cambio gramatical
  articles/azure-stack/user/azure-stack-solution-pipeline.md
Labels: Accepted, Linguistic Suggestion

#287 Actualización
  articles/governance/blueprints/create-blueprint-rest-api.md
Labels: Accepted, Linguistic Suggestion

#282 Actualización "SQL database technical overview"
  articles/sql-database/sql-database-technical-overview.md
Labels: Linguistic Suggestion, Partially Accepted

#292 Linea 402 mejor contexto
  articles/governance/policy/tutorials/create-and-manage.md
Labels: Linguistic Suggestion, Partially Accepted

#296 pequeño error de redacción
  articles/guides/developer/azure-developer-guide.md
Labels: Linguistic Suggestion, Partially Accepted

#300 Pequeño error de traducción y redacción
  articles/guides/developer/azure-developer-guide.md
Labels: Accepted, Linguistic Suggestion

#299 pequeño error de traducción
  articles/guides/developer/azure-developer-guide.md
Labels: In Progress, Linguistic Suggestion
