Repository MicrosoftDocs/azure-docs.es-es, pull requests merged in 2019-06, with the labels that each got.

#458 Fix mistranslation
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: Accepted

#455 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#456 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-sybase-connector.md
Labels: Accepted

#457 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#454 Fix Typo
  articles/aks/intro-kubernetes.md
Labels: Accepted, Linguistic Suggestion

#459 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted, Linguistic Suggestion

#460 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#461 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#464 Fix mistranslation
  articles/data-factory/v1/data-factory-stored-proc-activity.md
Labels: Accepted, Linguistic Suggestion

#463 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#462 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted, Linguistic Suggestion

#466 Fix mistranslation
  articles/event-grid/event-schema-container-registry.md
Labels: Accepted, Linguistic Suggestion

#465 Fix mistranslation
  articles/event-grid/event-schema-azure-maps.md
Labels: Accepted, Linguistic Suggestion

#468 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: In Progress

#470 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#469 Fix mistranslation
  articles/event-grid/subscription-creation-schema.md
Labels: In Progress

#471 Fix mistranslation
  articles/lab-services/devtest-lab-artifact-author.md
Labels: In Progress

#472 Fix mistranslation
  articles/logic-apps/logic-apps-custom-api-authentication.md
Labels: In Progress

#473 Fix mistranslation
  articles/logic-apps/logic-apps-exception-handling.md
Labels: In Progress

#474 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#475 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-as2-tracking-schemas.md
Labels: In Progress

#476 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#478 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-x12-tracking-schema.md
Labels: In Progress

#479 Fix mistranslation
  articles/managed-applications/create-uidefinition-elements.md
Labels: In Progress

#480 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#481 Fix mistranslation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: In Progress

#482 Fix mistranslation
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension.md
Labels: In Progress

#486 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: In Progress

#485 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-windows.md
Labels: In Progress

#484 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-linux.md
Labels: In Progress

#483 Fix mistranslation
  articles/service-fabric/service-fabric-cluster-nodetypes.md
Labels: In Progress

#488 Fix mistranslation
  articles/virtual-machines/extensions/chef.md
Labels: In Progress

#489 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: In Progress

#490 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linuxOstc.md
Labels: Accepted

#494 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-linux.md
Labels: Accepted, Linguistic Suggestion

#492 Fix mistranslation
  articles/virtual-machines/extensions/dsc-template.md
Labels: Accepted, Linguistic Suggestion

#493 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted, Linguistic Suggestion

#491 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-windows.md
Labels: Accepted, Linguistic Suggestion

#496 Fix mistranslation
  articles/virtual-machines/extensions/network-watcher-linux.md
Labels: In Progress

#495 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-windows.md
Labels: In Progress

#501 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/BingVoiceOutput.md
Labels: In Progress

#500 Fix mistranslation
  includes/data-factory-structure-for-rectangualr-datasets.md
Labels: In Progress

#499 Fix mistranslation
  articles/virtual-machines/extensions/oms-windows.md
Labels: In Progress

#497 Fix mistranslation
  articles/virtual-machines/extensions/network-watcher-windows.md
Labels: In Progress

#498 Fix mistranslation
  articles/virtual-machines/extensions/oms-linux.md
Labels: In Progress

#507 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: In Progress

#506 Fix mistranslation
  articles/analysis-services/analysis-services-async-refresh.md
Labels: In Progress

#505 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: In Progress

#504 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-blob-connector.md
Labels: In Progress

#503 Fix mistranslation
  articles/data-factory/v1/data-factory-amazon-simple-storage-service-connector.md
Labels: In Progress

#508 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: In Progress

#509 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: In Progress

#510 Fix mistranslation
  articles/data-factory/control-flow-if-condition-activity.md
Labels: In Progress

#511 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#512 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#513 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-definition-language.md
Labels: Accepted, Linguistic Suggestion

#514 Fix mistranslation
  articles/logic-apps/workflow-definition-language-functions-reference.md
Labels: Accepted

#515 Fix mistranslation
  articles/media-services/latest/media-services-event-schemas.md
Labels: Accepted, Linguistic Suggestion

#517 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#518 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted, Linguistic Suggestion

#520 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted, Linguistic Suggestion

#519 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#521 Fix mistranslation
  articles/azure-monitor/insights/solutions-solution-file.md
Labels: Accepted, Linguistic Suggestion

#502 Update durable-functions-concepts.md
  articles/azure-functions/durable/durable-functions-concepts.md
Labels: Accepted, Linguistic Suggestion

#522 Fix mistranslation
  articles/azure-monitor/log-query/unify-app-resource-data.md
Labels: Accepted

#523 Fix mistranslation
  articles/azure-monitor/platform/activity-log-export.md
Labels: Accepted

#524 Fix mistranslation
  articles/azure-monitor/platform/alerts-webhooks.md
Labels: Accepted

#525 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted
